# Generated by Django 3.0.5 on 2021-05-08 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usrprofile.django_resized
import usrprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=30)),
                ('Last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('contact', models.BigIntegerField(blank=True)),
                ('proforma_image', models.ImageField(blank=True, default=usrprofile.models.get_default_profile_image, null=True, upload_to='proforma/')),
                ('DOB', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('special_activity', models.TextField(blank=True, max_length=500)),
                ('specialist', models.CharField(blank=True, max_length=100)),
                ('available', models.CharField(choices=[('For hire', 'hire'), ('Professional', 'Professional'), ('student', 'Student')], default='For hire', max_length=30)),
                ('experience', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uploda_Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='none', upload_to='Resume/')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_resume', to='usrprofile.MyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=30)),
                ('skill_name', models.CharField(blank=True, max_length=150)),
                ('skill_dependency', models.CharField(blank=True, max_length=250)),
                ('skill_text', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myskills', to='usrprofile.MyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='MyExpreience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expreience', models.CharField(blank=True, max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('file', models.ImageField(default='none', upload_to=usrprofile.models.get_exp_document_filepath)),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_exp', to='usrprofile.MyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='MyEdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_class', models.CharField(blank=True, max_length=30)),
                ('board_name', models.CharField(blank=True, max_length=30)),
                ('year', models.IntegerField(blank=True)),
                ('percentage', models.CharField(max_length=30)),
                ('file', models.ImageField(default='none', upload_to=usrprofile.models.get_edu_document_filepath)),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_edu', to='usrprofile.MyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='MyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.BigIntegerField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('postal_code', models.IntegerField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usrprofile.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usrprofile.Country')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_address', to='usrprofile.MyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='MyActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(blank=True, max_length=50)),
                ('activity_url', models.URLField(default='none', max_length=100)),
                ('activity_head_image', usrprofile.django_resized.ResizedImageField(crop=None, default='none', force_format=None, keep_meta=True, quality=-1, size=[1080, 1080], upload_to='HeadImage/')),
                ('activity_head_report', models.FileField(default='none', upload_to='Report/')),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_activity', to='usrprofile.MyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Iam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iam', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iam', to='usrprofile.MyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Follow', models.CharField(max_length=50)),
                ('myprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hobbies', to='usrprofile.MyProfile')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_set', to='usrprofile.Country'),
        ),
    ]
