# Generated by Django 3.0.5 on 2021-03-28 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('First_name', models.CharField(blank=True, max_length=30)),
                ('Last_name', models.CharField(blank=True, max_length=30)),
                ('proforma_image', models.ImageField(blank=True, default=home.models.get_default_profile_image, null=True, upload_to='proforma/')),
                ('bio', models.TextField(blank=True)),
                ('domain', models.ManyToManyField(related_name='field', to='home.Domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
